// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaCpXVO958hbPsjgtnRptsBns83yQ7lwc',
    appId: '1:153028996927:web:00623256f171ca6a8d6d8a',
    messagingSenderId: '153028996927',
    projectId: 'flutter-project-11bf0',
    authDomain: 'flutter-project-11bf0.firebaseapp.com',
    storageBucket: 'flutter-project-11bf0.firebasestorage.app',
    measurementId: 'G-W1PR65DKXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpd_YGd-UhCg9yvIYejy7517eQummwjYI',
    appId: '1:153028996927:android:7d1a6ba3cc8dc3b38d6d8a',
    messagingSenderId: '153028996927',
    projectId: 'flutter-project-11bf0',
    storageBucket: 'flutter-project-11bf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0vdprjR7TGSuFcHYFaW6JOmll-iwHcI4',
    appId: '1:153028996927:ios:7c96a2875e6df0bb8d6d8a',
    messagingSenderId: '153028996927',
    projectId: 'flutter-project-11bf0',
    storageBucket: 'flutter-project-11bf0.firebasestorage.app',
    iosBundleId: 'com.classroom.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0vdprjR7TGSuFcHYFaW6JOmll-iwHcI4',
    appId: '1:153028996927:ios:57f55d9442b8abea8d6d8a',
    messagingSenderId: '153028996927',
    projectId: 'flutter-project-11bf0',
    storageBucket: 'flutter-project-11bf0.firebasestorage.app',
    iosBundleId: 'com.example.providerTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaCpXVO958hbPsjgtnRptsBns83yQ7lwc',
    appId: '1:153028996927:web:a2141dd10f5d00ae8d6d8a',
    messagingSenderId: '153028996927',
    projectId: 'flutter-project-11bf0',
    authDomain: 'flutter-project-11bf0.firebaseapp.com',
    storageBucket: 'flutter-project-11bf0.firebasestorage.app',
    measurementId: 'G-PX8XPWHQRS',
  );
}
